### ISSUE TITLE
Update for AFNetworking 3.1.0

### ISSUE THREAD

**Issue by GabeJacobs** [andresbrun/ABMSoundCloudAPI#10]
AFNetworking is on 3.1.0 now. It's a pretty great new release and it shouldn't be dependent on  < 2.6

**Comment by andresbrun** [comment]
I will update it asap ;) thanks!

**Comment by andresbrun** [comment]
Done, you can find the version 1.0+ supports AFNetworking 3.0+

**Comment by degnarraer** [comment]
Sure would like Background support. :-)
