### ISSUE TITLE
ABMSoundCloudAPISingleton not included?

### ISSUE THREAD

**Issue by GabeJacobs** [andresbrun/ABMSoundCloudAPI#11]
Hey,

It seems as though ABMSoundCloudAPISingleton isn't included in the cocoapod? Then when trying to add it manually I'm getting linker errors. Any clue?
- Gabe

**Comment by andresbrun** [comment]
Sorry for the delay Gabe. `ABMSoundCloudAPISingleton` is just an example of how to integrate it, actually not the best as singleton should be avoided in this case but I choose it for the simplicity's sake. Not sure why gives you an error though, can you send me an screenshot?
