### ISSUE TITLE
Error credential

### ISSUE THREAD

**Issue by PatrickRguez** [andresbrun/ABMSoundCloudAPI#8]
Hi. I recieve:

ABMSoundCloudAPI[12000:4731538] Unable to fetch credential with identifier "SoundClount_Crendentials" (Error -25300)

Why? 

Thank you very much

**Comment by PatrickRguez** [comment]
I don´t handle the redirect URI.

**Comment by andresbrun** [comment]
Hi PatrickRguez, sorry for the delay. This error is related with AFOAuthCredential, the library I am using to handle oauth authentication. I have to dig a little bit more to figure out what's going on. Maybe just using the last version it works.

**Comment by andresbrun** [comment]
Sorry, I wasn't be able to reproduce your error. I am using the last version of AFOAuthCredential in version 1.0 of the library. Could you try with that one and tell me if the error still happens?
